#pragma once
#include "1_hello_window.h"
#include "2_hello_triangle.h"
#include "3_hello_rectangle.h"
#include "4_shader_uniform.h"
#include "5_shader_interpolation.h"
#include "6_texture.h"
#include "7_texture_combined.h"
#include "8_transformations.h"